apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  application: movie-info-service
  revision: ${GIT_COMMIT_FORMATTED} # replaced during jenkins pipeline
  env: ${KUBERNETES_CONTEXT} # replaced during jenkins pipeline
  version: ${POM_VERSION} # replaced during jenkins pipeline
  owner: movies-squad
commonAnnotations:
  author: "Dhiego Duarte"
  email: "dhiego.duarte.terceiros@claro.com.br"
  company: "Claro BR"
resources:
- ./movie-info-service-cluster-ip-service.yaml
- ./movie-info-service-service-account.yaml
- ./movie-info-service-deployment.yaml