apiVersion: v1
kind: Service
metadata:
  name: movie-info-service-cluster-ip-service
  annotations:
    author: DhiegoDuarte
    email: dhiegoduarte@gmail.com
    company: ClaroBR
  labels:
    application: movie-info-service
    revision: TODO_COMO_COLOCAR_O_COMMIT_AQUI #4c511f16ef2644854d04cabebfcecc82be0eb04f
    env: stage
    version: "1.0.0"
    owner: movies-squad
spec:
  selector:
    component: movie-info-service-pod
  ports:
    - name: http
      port: 8082 # nodePort: 30082
  type: ClusterIP #NodePort

