apiVersion: v1
kind: Service
metadata:
  name: movie-info-service-cluster-ip-service
spec:
  selector:
    component: movie-info-service-pod
  ports:
    - name: http
      port: 8082 # nodePort: 30082
  type: ClusterIP #NodePort

