apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-service-deployment
spec:
  selector:
    matchLabels:
      component: movie-info-service-pod
  replicas: 1
  template: 
    metadata:
      labels:
        component: movie-info-service-pod
    spec:
      serviceAccountName: movie-info-service-service-account
      securityContext:
        runAsNonRoot: true 
        runAsUser: 1000 
        runAsGroup: 3000 
      containers:
      - name: movie-info-service-container
        # image: 52.14.127.219/movie-info-service/movie-info-service-image # utilizado no pipeline do Jenkins da AWS Claro Br
        image: harbor.claro.com.br/poc-arquitetura/movie-info-service-img # harbor.claro.com.br/movie-info-service/movie-info-service-img
        # image: dhiegoduarte/movie-info-service-img 
        securityContext: 
          allowPrivilegeEscalation: false
          # privileged: false (default)
          # readOnlyRootFilesystem: true # tomcat tenta criar /tmp Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp
          capabilities:
            drop:
            - ALL
          #   add: 
          #   - NET_BIND_SERVICE  # permite portas < 1000 (80 e 443). MS POC configurados com 8081, 8082 e 8083
        resources: # QoS Guaranteed limit e request iguais
          limits:
            cpu: 100m
            memory: 200Mi 
          requests:
            cpu: 100m
            memory: 200Mi 
        env: 
        - name: JAEGER_AGENT_HOST   # NOTE: Point to the Agent daemon on the Node
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT # nao deve usar desta forma. Utilizar config-map conforme o movie-catalog-service-deployment acima
          value: '6831'
        - name: JAEGER_SERVICE_NAME # nao deve usar desta forma. Utilizar config-map conforme o movie-catalog-service-deployment acima
          value: movie-info-service
